@baseUrl = http://localhost:3000

### Criar uma nova postagem
POST {{baseUrl}}/posts
Content-Type: application/json

{
  "title": "2 Postagem com variável",
  "content": "Usando variáveis para deixar o arquivo mais limpo.",
  "author_id": 1
}

### Testar a rota principal
GET {{baseUrl}}/posts

### Obter uma postagem específica (sucesso)
GET {{baseUrl}}/posts/1

### Obter uma postagem específica (erro 404)
GET {{baseUrl}}/posts/9999

### Atualizar uma postagem
PUT {{baseUrl}}/posts/1
Content-Type: application/json

{
  "title": "Este Título Foi Atualizado",
  "content": "O conteúdo também foi modificado através do endpoint PUT."
}

### Deletar uma postagem
DELETE {{baseUrl}}/posts/1