services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: blog_db
    environment:
      # Lê as variáveis diretamente do seu arquivo .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
  
  # Serviço da nossa Aplicação Node.js
  app:
    build: .
    container_name: blog_app
    ports:
      - "3000:3000"
    environment:
      # O Docker Compose também passa as variáveis para o container da aplicação
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
    depends_on:
      - db

volumes:
  pgdata: