@baseUrl = http://localhost:3000

### Criar uma nova postagem
POST {{baseUrl}}/professor/posts
Content-Type: application/json

{
  "title": "3 novo posts",
  "content": "Usando variáveis para deixar o arquivo mais limpo.",
  "author_id": 1
}

### Testar a rota principal
GET {{baseUrl}}/professor/posts

### Obter uma postagem específica (sucesso)
GET {{baseUrl}}/professor/posts/1

### Obter uma postagem específica (erro 404)
GET {{baseUrl}}/professor/posts/9999

### Atualizar uma postagem
PUT {{baseUrl}}/professor/posts/1
Content-Type: application/json

{
  "title": "Este Título Foi ajustado",
  "content": "O conteúdo também foi modificado através do endpoint PUT.",
  "status":"inativo"
}

### Deletar uma postagem
DELETE {{baseUrl}}/professor/posts/1

### Buscar posts por palavra-chave
GET {{baseUrl}}/professor/posts/search?q=3

### Obter usuarios cadastrados
GET {{baseUrl}}/users/

###criar um novo usuário
POST {{baseUrl}}/users/
Content-Type: application/json

{
  "name": "Felipe Seiji",
  "email": "Felipe@teste.com",
  "password_hash": "1121",
  "role":"professor"
  }

### Atualizar usuário
PUT {{baseUrl}}/users/1
Content-Type: application/json

{
  "name": "Camila",
  "email": "cacazinha@gmail.com",
  "password_hash": "2806",
  "role": "professor"
}
### Deletar um usuário
DELETE {{baseUrl}}/users/1

### Testar a rota principal - alunos
GET {{baseUrl}}/aluno/posts

### Obter uma postagem específica - aluno
GET {{baseUrl}}/aluno/posts/1

### Buscar posts por palavra-chave
GET {{baseUrl}}/professor/posts/search?q=insi
