@baseUrl = http://localhost:3000
@professorToken = {{professorToken}}

// AUTENTICAÇÃO
###
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Felipe Seiji",
  "email": "seijimatie@mail.com",
  "password": "fe280699",
  "role": "professor"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "seijimatie@mail.com",
  "password": "fe280699"
}

# Copie o token JWT retornado e cole abaixo:
# @professorToken = 

# ROTA PROFESSORES (JWT obrigatório)
###
GET {{baseUrl}}/professor/posts
Authorization: Bearer {{professorToken}}

###
POST {{baseUrl}}/professor/posts
Authorization: Bearer {{professorToken}}
Content-Type: application/json

{
  "title": "O Corpo Humano: Sistemas e Órgãos",
  "content": "Uma visão geral sobre os principais sistemas do corpo humano: digestório, respiratório, circulatório e nervoso. Como eles trabalham em conjunto?",
  "author_id": 128,
  
}

###
GET {{baseUrl}}/professor/posts/140
Authorization: Bearer {{professorToken}}

###
GET {{baseUrl}}/professor/posts/9999
Authorization: Bearer {{professorToken}}

###
PUT {{baseUrl}}/professor/posts/140
Authorization: Bearer {{professorToken}}
Content-Type: application/json

{
  "title": "O Corpo Humano: Sistemas e Órgãos",
  "content": "Uma visão geral sobre os principais sistemas do corpo humano: digestório, respiratório, circulatório e nervoso. Como eles trabalham em conjunto?",
  "status": "inativo"
}

###
DELETE {{baseUrl}}/professor/posts/140
Authorization: Bearer {{professorToken}}

###
GET {{baseUrl}}/professor/posts/search?q=corpo humano  
Authorization: Bearer {{professorToken}}

# ROTA USERS (JWT obrigatório)
###
GET {{baseUrl}}/users/
Authorization: Bearer {{professorToken}}

###
POST {{baseUrl}}/users/
Authorization: Bearer {{professorToken}}
Content-Type: application/json

{
  "name": "Gustavo Guanabara",
  "email": "guanabara@mail.com",
  "password_hash": "gafanhotos123",
  "role": "professor"
}

###
PUT {{baseUrl}}/users/129
Authorization: Bearer {{professorToken}}
Content-Type: application/json

{
  "name": "Gustavo Guanabara Silva",
  "email": "guanabara@mail.com",
  "password": "gafanhotos4421",
  "role": "professor"
}

###
DELETE {{baseUrl}}/users/129
Authorization: Bearer {{professorToken}}

# ROTA ALUNOS (Acesso livre)
###
GET {{baseUrl}}/aluno/posts

###
GET {{baseUrl}}/aluno/posts/141

###
GET {{baseUrl}}/aluno/posts/search?q=corpo humano